% test Rutger
clear all
close all
clc

%% system

g = 2.5; lambda = 1.5;
sys = tf(g,[1, 1/lambda])

%% Variable preferences
P = 4;    
N = 2000;
fs = 20; %Hz
F = 800; 

f0 = fs/N;
Ts = 1/fs;
t = 0:Ts:(P*N-1)*Ts;
f = 0:f0:fs-f0;

k = 1:F;

%% Fast creation of input signal u
Umss = zeros(N,1);

phases = -k.*(k-1).*pi/F;
Umss = zeros(N,1);
Umss(2:F+1) = exp(1i*phases);
umss = 2*real(ifft(Umss)); umss = umss/std(umss);

u_fast = repmat(umss,P,1);

figure; plot(u_fast)
title('Total Signal u of fast multiphase');

y_fast = lsim(sys,u_fast,t);

figure; plot(u_fast(end-N+1:end))
title('Steady state plot of u by fast multiphase');
figure; plot(y_fast(end-N+1:end))
title('Steady state plot of y by fast multiphase');

%% Sum of sine creation for input signal
upre=zeros(N*P,1);

for j = 1:F
     upre= upre + sin(2 * pi * f0 * t' * j + phases(j));
end
%upre=real(upre); 
u_sum = upre / std(upre);

figure; plot(u_sum)
title('Total Signal u of sine summation multiphase');

y_sum = lsim(sys,u_sum,t);

figure; plot(u_sum(end-N+1:end))
title('Steady state plot of u by simution of sine multiphase');
figure; plot(y_sum(end-N+1:end))
title('Steady state plot of y by simution of sine multiphase');

%% Read data generated by pyton scripts
clear y_python u_python u_test
u_test=readtable(['u_transient_test2']);
u_python=table2array(u_test);
y_python=table2array(readtable('y_trantsient_test2'));

%% Select which u to use for plots
clear u y U Y G G_magnitude G_phase 

u = u_sum;

y = lsim(sys,u,t);
%y=y_python;

%% FRF


% Frequency Response Function (FRF) Calculation
Y = fft(y(end-N+1:end));
U = fft(u(end-N+1:end));
G = Y./U;

% Plot for the used frequencies in Gd
figure; semilogx(f,db(U))
xlim([0,fs/2])

% Magnitude and Phase for FRF
G_magnitude = abs(G); % Magnitude
G_phase = angle(G); % Phase in radians

% Plot Magnitude and Phase Response for both sys and FRF
figure;

% Bode Plot for Designed System
[mag,phase,wout] = bode(sys,{min(f)*2*pi, max(f)*2*pi});
mag = squeeze(mag);
phase = squeeze(phase);

% Overlay FRF Magnitude
subplot(2,1,1); % Magnitude plot
semilogx(wout, 20*log10(mag), 'b', f*2*pi, 20*log10(G_magnitude), 'r--');
ylim([-40,40])
ylabel('Magnitude (dB)');
legend('System TF', 'Simulated FRF');
title('Magnitude Response');

% Overlay FRF Phase
subplot(2,1,2); % Phase plot
semilogx(wout, (phase), 'b', f*2*pi, rad2deg(G_phase), 'r--');
xlabel('Frequency (rad/s)');
ylabel('Phase (degrees)');
legend('System TF', 'Simulated FRF');
title('Phase Response');

crest=max(u)/rms(u)

%% Bode analysis of discrete

%H = tf([2.5],[1 1.5]);
%Hd = c2d(H,0.05,'zoh');

%bode(H,Hd)