% test Rutger
clear all
close all
clc

%% system

g = 2.5; lambda = 1.5;
sys = tf(g,[1, 1/lambda])

%% Variable preferences
P = 4;    
N = 2000;
fs = 20; %Hz
F = 800; 

f0 = fs/N;
Ts = 1/fs;
t = 0:Ts:(P*N-1)*Ts;
f = 0:f0:fs-f0;

k = 1:F;

%% Fast creation of input signal u
Umss = zeros(N,1);

phases = -k.*(k-1).*pi/F;
Umss = zeros(N,1);
Umss(2:F+1) =exp(1i*phases);
umss = 2*real(ifft(Umss)); umss = umss/std(umss);

u_fast = repmat(umss,P,1);

figure; plot(u_fast)
title('Total Signal u of fast multiphase');

y_fast = lsim(sys,u_fast,t);

figure; plot(u_fast(end-N+1:end))
title('Steady state plot of u by fast multiphase');
figure; plot(y_fast(end-N+1:end))
title('Steady state plot of y by fast multiphase');

%% Sum of sine creation for input signal
upre=zeros(N*P,1);

for j = 1:F
     upre= upre + sin(2 *pi * f0 * t' * j + phases(j)+pi/2);
end
%upre=real(upre); 
u_sum = upre / std(upre);

figure; plot(u_sum)
title('Total Signal u of sine summation multiphase');

y_sum = lsim(sys,u_sum,t);

figure; plot(u_sum(end-N+1:end))
title('Steady state plot of u by simution of sine multiphase');
figure; plot(y_sum(end-N+1:end))
title('Steady state plot of y by simution of sine multiphase');

%% Read data generated by pyton scripts
clear y_python u_python u_test G_tf G_python mag phase
u_test=readtable(['u_trans_solvertest']);
u_python=table2array(u_test);
y_python=table2array(readtable('y_trans_solvertest'));

%% Select which u to use for plots
clear u y U Y G G_magnitude G_phase 

u = u_sum;

y = lsim(sys,u,t);
%y=y_python;

%% FRF by simulatioin

% Frequency Response Function (FRF) Calculation
Y = fft(y(end-N+1:end));
U = fft(u(end-N+1:end));
G = Y./U;

% Plot for the used frequencies in Gd
figure; semilogx(f,db(U))
xlim([0,fs/2])

% Plot transient detection
y_steady=y(end-N+1:end);
y_steady_total=repmat(y_steady,P,1);
figure; plot(t,(y_steady_total-y))
title('Transien y - repeated steady state y, y from python')

% Magnitude and Phase for FRF
mag_G = abs(G); % Magnitude
phase_G = angle(G); % Phase in radians

%% Transfer function FRF

% Bode Plot for Designed System
[mag,phase,wout] = bode(sys,f*2*pi);
mag_tf = squeeze(mag);
phase_tf = deg2rad(squeeze(phase));
G_tf=mag_tf.*exp(1i*phase_tf);


%% Visualize the different 


% Plot Magnitude and Phase Response for both sys and FRF
figure;

% Overlay FRF Magnitude
subplot(2,1,1); % Magnitude plot
semilogx(wout, 20*log10(mag_tf), 'b', f*2*pi, 20*log10(mag_G), 'r--');
ylim([-40,40])
ylabel('Magnitude (dB)');
legend('System TF', 'Simulated FRF');
title('Magnitude Response');

% Overlay FRF Phase
subplot(2,1,2); % Phase plot
semilogx(wout,rad2deg(phase_tf), 'b', f*2*pi, rad2deg(phase_G), 'r--');
xlabel('Frequency (rad/s)');
ylabel('Phase (degrees)');
legend('System TF', 'Simulated FRF');
title('Phase Response');

figure;
semilogx(f, 20*log10(mag_tf), 'b', f, 20*log10(mag_G), 'r--',f, 20*log10(abs(G-G_tf)), 'd')
ylim([-150,200])
xlim([0.01,100])
ylabel('Magnitude (dB)');
legend('System TF', 'Simulated FRF','|G-G_{tf}|');
title('Matlab analysis for the FRF using lsim solver');

crest=max(u)/rms(u)

%% Bode analysis of discrete

%H = tf([2.5],[1 1.5]);
%Hd = c2d(H,0.05,'zoh');

%bode(H,Hd)

%%

% %%
% G_python = readtable('G_steady_solvertest', 'ReadVariableNames', false);
% G_python = G_python{:, 2};  % Extracts the second column as an array
% 
% % Assuming 'cellArray' is your 2000x1 cell array with complex number strings
% 
% % Initialize an array to hold the complex numbers
% complexArray = zeros(2000, 1);
% 
% % Convert each cell to a complex number
% for i = 1:2000
%     complexArray(i) = str2num(G_python{i});
% end
% 
% G_python=complexArray;
% G=G_python;
% %%
% Gtf_python = readtable('Gtf_steady_solvertest', 'ReadVariableNames', false);
% Gtf_python = Gtf_python{:, 2};  % Extracts the second column as an array
% 
% % Assuming 'cellArray' is your 2000x1 cell array with complex number strings
% 
% % Initialize an array to hold the complex numbers
% complexArray = zeros(2000, 1);
% 
% % Convert each cell to a complex number
% for i = 1:2000
%     complexArray(i) = str2num(Gtf_python{i});
% end
% 
% Gtf_python=complexArray;
% G_tf=Gtf_python;
% 
% % Bode Plot for Designed System
% [mag,phase,wout] = bode(sys,f*2*pi);
% %mag = squeeze(mag);
% mag = table2array(readtable('magtf_steady_solvertest'));
% mag = 10.^(mag/20);
% phase = table2array(readtable('phasetf_steady_solvertest'));
% G_tf=mag.*exp(1i*phase);
% %phase = squeeze(phase);
% %G_tf=zeros(N,1);
% %G_tf(1:N)=mag.*exp(1i.*phase);
